apiVersion: v1
kind: Service
metadata:
  name: release-name-service
spec:
  selector:
    app.kubernetes.io/instance: release-name
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000